### ISSUE TITLE
【Main_1to5 】クエストレビュー

### ISSUE THREAD

**Issue by VRAcademy** [ohtamaton/vrws0128#1]
１〜５までのクエストを確認しました。
そして概ねすべてのクエスト実装出来ていることを確認しました。

ここで追加リクエストですが、今現在の実装ではどこに視線先を表すポイント（UI）が
表示されていないことにより、どこにフォーカスを合わせればいいのかわかりません。
ですので、視線先表すためのUIを実装し、今現在表示しているサークル内に入ったら
アイコンがアニメーションするに変更してみてください。
さらにボタンが選択されたら、現在作成してあるMain_6にシーンが遷移する処理に変更してみてください。
[サンプルイメージ](https://dl.dropboxusercontent.com/u/41137116/kadinche/focus.png)

**Comment by VRAcademy** [comment]
これが出来たらクエスト１〜５はクリアです。

**Comment by ohtamaton** [comment]
ご指摘の通り、視線先を表すUIを追加し、ボタンがおされたら、
Main_6に遷移するように変更しました。

以上、再度レビューのほどよろしくお願いいたします。

**Comment by VRAcademy** [comment]
実装を確認しました。OKです。
余談になりますが、モノラル画像において、同じ座標軸にカメラを置いてますが、０．７５未満の数値でズラして見るとどう見えるのか試してみると面白いです。

**Comment by ohtamaton** [comment]
確認ありがとうございます。ずらすと視差で立体に見えるんですかね？試してみようかと思います。
クエストとしてはクリアとのことなのでcloseします。
