### ISSUE TITLE
【Main_7】クエストレビュー

### ISSUE THREAD

**Issue by VRAcademy** [ohtamaton/vrws0128#3]
実装内容を確認しました。
実機にて確認したところ、ピンチイン・アウトによるカメラの画角の変更が出来ていることを確認しました。
しかし、画面のタップによるUI操作やスワイプなどによるカメラの回転処理の実装を確認できませんでした。

ですので画面タッチ操作でもジャイロと同じような回転処理が出来る処理を実装してみてください。

**Comment by ohtamaton** [comment]
レビューありがとうございました。

GameManagerにattachしたMouseManagerにて実装しており、私の端末では動作確認
できておりましたが、一部プラットフォーム分岐としてUNITY_IOSを記載していなかった
ので差分が出たのかもしれませんので修正いたしました。

タップ操作は現在、左カメラのhotSpotをクリックすると動作する実装となっています。

以上、再度レビューをお願いいたします。

**Comment by VRAcademy** [comment]
修正確認しました。iOSでの動作を確認しました。
ちょっとクリックしでも拡大アニメーションが出てしまうのが気になりましたが、
クエスト内容的にはそこは重視してないのでOKです。
クリアです

**Comment by ohtamaton** [comment]
確認ありがとうございます。今後流用できるようにライブラリ化も兼ねて整理する際に改善してみます。
クエストとしてはクリアとのことなのでcloseします。
